# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='project',
            field=models.CharField(default='', max_length=100),
        ),
    ]
