# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=100)),
                ('file_path', models.FilePathField(match='*.*', max_length=200, path='*')),
                ('prob', models.DecimalField(decimal_places=3, max_digits=4)),
                ('reason', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=100)),
                ('pull_request', models.CharField(max_length=100)),
                ('commit', models.CharField(max_length=100)),
                ('prob', models.DecimalField(decimal_places=3, max_digits=4)),
                ('reason', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pullrequest',
            unique_together=set([('owner', 'project', 'pull_request', 'commit')]),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set([('owner', 'project', 'file_path')]),
        ),
    ]
