# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-29 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=1000)),
                ('content_length', models.IntegerField()),
                ('tag', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='RawCommentItem',
        ),
    ]
