# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0002_auto_20180815_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.FilePathField(max_length=200, path='(\\/[a-zA-Z0-9]+)*'),
        ),
    ]
