# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0002_auto_20180821_1606'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='training_m3',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='training_m3',
            name='reviewId',
        ),
        migrations.AlterUniqueTogether(
            name='training_m4',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='training_m4',
            name='reviewId',
        ),
        migrations.DeleteModel(
            name='Training_m3',
        ),
        migrations.DeleteModel(
            name='Training_m4',
        ),
    ]
