# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0002_auto_20181001_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('discussion_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('content', models.CharField(default='', max_length=5000)),
                ('content_length', models.IntegerField(default=0)),
                ('is_inline_discussion', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField()),
                ('reviewed_time', models.DateTimeField(default=None, null=True)),
                ('project', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DiscussionTag',
            fields=[
                ('tag_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('pr_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('project', models.CharField(default='', max_length=100)),
                ('commit_hash', models.CharField(default='', max_length=100)),
                ('creation_time', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='discussion',
            name='pr',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crml_api.PullRequest'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='predicted',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_predicted', to='crml_api.DiscussionTag'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_true', to='crml_api.DiscussionTag'),
        ),
    ]
