# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-29 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0003_code_image_issue_link_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='content',
            new_name='code_content',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='alt',
            new_name='image_alt',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='src',
            new_name='image_src',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='content',
            new_name='issue_content',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='content',
            new_name='link_content',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='content',
            new_name='people_content',
        ),
        migrations.RemoveField(
            model_name='code',
            name='content_length',
        ),
    ]
