# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0003_review_reviewed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewed_time',
            field=models.DateTimeField(),
        ),
    ]
