# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-29 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0004_auto_20180430_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='project',
        ),
    ]
