# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0004_remove_discussion_pr'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='pr_id',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
