# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 09:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0005_auto_20180605_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewed_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 5, 9, 20, 20, 162999, tzinfo=utc)),
        ),
    ]
