# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0005_discussion_pr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='pr_id',
            field=models.CharField(max_length=50),
        ),
    ]
