# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-29 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0005_remove_review_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='content',
            new_name='review_content',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='content_length',
            new_name='review_content_length',
        ),
    ]
