# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0005_auto_20180823_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance_m1',
            name='avg_f1',
        ),
        migrations.RemoveField(
            model_name='performance_m2',
            name='avg_f1',
        ),
    ]
