# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0006_auto_20180823_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance_unbalanced_learn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('binary', models.BooleanField(default=False)),
                ('technique', models.CharField(default='', max_length=100)),
                ('sa_f1', models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True)),
                ('og_f1', models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True)),
                ('vr_f1', models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True)),
                ('sl_f1', models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True)),
                ('tx_f1', models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True)),
                ('ld_f1', models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True)),
                ('sp_f1', models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True)),
                ('ck_f1', models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True)),
                ('rs_f1', models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True)),
                ('lg_f1', models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True)),
                ('it_f1', models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True)),
                ('tr_f1', models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True)),
                ('pc_f1', models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True)),
                ('ot_f1', models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crml_api.Algorithm')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='performance_unbalanced_learn',
            unique_together=set([('algorithm', 'size', 'binary')]),
        ),
    ]
