# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0007_delete_pullrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('pr_id', models.CharField(max_length=50)),
                ('project', models.CharField(default='', max_length=100)),
                ('commit_hash', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
