# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0007_auto_20180906_0825'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performance_unbalanced_learn',
            unique_together=set([('algorithm', 'size', 'binary', 'technique')]),
        ),
    ]
