# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0008_auto_20180430_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='reviewId',
        ),
        migrations.AlterField(
            model_name='code',
            name='reviewId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_content', to='crml_api.Review'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='reviewId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_content', to='crml_api.Review'),
        ),
        migrations.AlterField(
            model_name='link',
            name='reviewId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_content', to='crml_api.Review'),
        ),
        migrations.AlterField(
            model_name='people',
            name='reviewId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_content', to='crml_api.Review'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
