# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0008_auto_20180906_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance_m1',
            name='avg_f1',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='performance_m2',
            name='avg_f1',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='performance_unbalanced_learn',
            name='avg_f1',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True),
        ),
    ]
