# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0009_auto_20180605_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewed_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
