# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0010_auto_20180430_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='codeContents',
        ),
        migrations.AddField(
            model_name='code',
            name='code_content',
            field=models.CharField(default='ss', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='reviewId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crml_api.Review'),
        ),
        migrations.AlterField(
            model_name='link',
            name='reviewId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crml_api.Review'),
        ),
        migrations.AlterField(
            model_name='people',
            name='reviewId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crml_api.Review'),
        ),
        migrations.DeleteModel(
            name='CodeContent',
        ),
    ]
