# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0010_auto_20180912_1620'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performance_m2',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='performance_m2',
            name='algorithm',
        ),
        migrations.DeleteModel(
            name='Performance_m2',
        ),
    ]
