# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0010_delete_pullrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_id', models.CharField(max_length=50)),
                ('project', models.CharField(max_length=100)),
                ('commit_hash', models.CharField(max_length=100)),
                ('creation_time', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
