# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0011_auto_20180912_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance_m2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('binary', models.BooleanField(default=False)),
                ('avg_sa_f1', models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True)),
                ('avg_og_f1', models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True)),
                ('avg_ts_f1', models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True)),
                ('avg_lg_f1', models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True)),
                ('avg_pc_f1', models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True)),
                ('avg_ot_f1', models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True)),
                ('avg_avg_f1s', models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True)),
                ('lower_extreme', models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True)),
                ('lower_quartile', models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True)),
                ('median', models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True)),
                ('upper_quartile', models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True)),
                ('upper_extreme', models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crml_api.Algorithm')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='performance_m2',
            unique_together=set([('algorithm', 'size', 'binary')]),
        ),
    ]
