# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0011_pullrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='creation_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='pr_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
