# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0011_auto_20180430_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_src', models.CharField(max_length=100)),
                ('image_alt', models.CharField(max_length=100)),
                ('reviewId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crml_api.Review')),
            ],
        ),
    ]
