# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0012_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code_content',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='people',
            name='people_content',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_content',
            field=models.CharField(max_length=3000),
        ),
    ]
