# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0012_auto_20181004_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('commit_hash', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('prob', models.DecimalField(decimal_places=3, max_digits=4)),
                ('predict_as', models.CharField(max_length=1)),
                ('lime', models.CharField(max_length=200)),
            ],
        ),
    ]
