# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0013_auto_20180607_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewed_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
