# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0014_auto_20180913_0313'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performance_m1',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='performance_m1',
            name='algorithm',
        ),
        migrations.AlterUniqueTogether(
            name='performance_m2',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='performance_m2',
            name='algorithm',
        ),
        migrations.AlterUniqueTogether(
            name='performance_unbalanced_learn',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='performance_unbalanced_learn',
            name='algorithm',
        ),
        migrations.AlterUniqueTogether(
            name='training_m1',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='training_m1',
            name='reviewId',
        ),
        migrations.AlterUniqueTogether(
            name='training_m2',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='training_m2',
            name='reviewId',
        ),
        migrations.RenameField(
            model_name='performance',
            old_name='size',
            new_name='testing_size',
        ),
        migrations.AddField(
            model_name='performance',
            name='avg_avg_f1s',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='avg_lg_f1',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='avg_og_f1',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='avg_ot_f1',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='avg_pc_f1',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='avg_sa_f1',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='avg_ts_f1',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='evaluation_method',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performance',
            name='extraction_method',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performance',
            name='lower_extreme',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='lower_quartile',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='median',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='training_size',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performance',
            name='upper_extreme',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='upper_quartile',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='algorithm',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='performance',
            name='accuracy',
        ),
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together=set([('algorithm', 'extraction_method', 'evaluation_method', 'training_size', 'testing_size')]),
        ),
        migrations.DeleteModel(
            name='Algorithm',
        ),
        migrations.DeleteModel(
            name='Performance_m1',
        ),
        migrations.DeleteModel(
            name='Performance_m2',
        ),
        migrations.DeleteModel(
            name='Performance_unbalanced_learn',
        ),
        migrations.DeleteModel(
            name='Training_m1',
        ),
        migrations.DeleteModel(
            name='Training_m2',
        ),
    ]
