# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0014_auto_20180607_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='training_size',
            field=models.IntegerField(default=0),
        ),
    ]
