# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0014_commit_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.CharField(max_length=100, null=True, verbose_name='Project')),
                ('File', models.CharField(max_length=100, null=True, verbose_name='File')),
                ('Prob', models.FloatField(null=True, verbose_name='Prob')),
                ('Reason', models.CharField(max_length=255, null=True, verbose_name='Reason')),
                ('Release', models.CharField(max_length=100, null=True, verbose_name='Release')),
                ('Date', models.DateField(null=True, verbose_name='Date')),
                ('COMM', models.FloatField(null=True, verbose_name='COMM')),
                ('ADEV', models.FloatField(null=True, verbose_name='ADEV')),
                ('DDEV', models.FloatField(null=True, verbose_name='DDEV')),
                ('ADD', models.FloatField(null=True, verbose_name='ADD')),
                ('DEL', models.FloatField(null=True, verbose_name='DEL')),
            ],
        ),
    ]
