# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 05:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0014_auto_20180501_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagId', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=500)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='is_inline_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crml_api.Tag'),
        ),
        migrations.AddField(
            model_name='training',
            name='reviewId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crml_api.Review'),
        ),
        migrations.AlterUniqueTogether(
            name='training',
            unique_together=set([('reviewId', 'feature')]),
        ),
    ]
