# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0015_review_training_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('algorithmId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('algorithmn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crml_api.Algorithm')),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='training_size',
        ),
        migrations.AddField(
            model_name='review',
            name='performance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crml_api.Performance'),
        ),
        migrations.AlterUniqueTogether(
            name='performance',
            unique_together=set([('algorithmn', 'size')]),
        ),
    ]
