# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0015_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='ADD',
            field=models.FloatField(default=None, null=True, verbose_name='ADD'),
        ),
        migrations.AlterField(
            model_name='release',
            name='ADEV',
            field=models.FloatField(default=None, null=True, verbose_name='ADEV'),
        ),
        migrations.AlterField(
            model_name='release',
            name='COMM',
            field=models.FloatField(default=None, null=True, verbose_name='COMM'),
        ),
        migrations.AlterField(
            model_name='release',
            name='DDEV',
            field=models.FloatField(default=None, null=True, verbose_name='DDEV'),
        ),
        migrations.AlterField(
            model_name='release',
            name='DEL',
            field=models.FloatField(default=None, null=True, verbose_name='DEL'),
        ),
        migrations.AlterField(
            model_name='release',
            name='Date',
            field=models.DateField(default=None, null=True, verbose_name='Date'),
        ),
    ]
