# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0015_auto_20180501_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='review',
            old_name='reviewed',
            new_name='extracted',
        ),
        migrations.RemoveField(
            model_name='review',
            name='tag',
        ),
        migrations.AddField(
            model_name='reviewtag',
            name='reviewId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crml_api.Review', unique=True),
        ),
        migrations.AddField(
            model_name='reviewtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crml_api.Tag'),
        ),
        migrations.AddField(
            model_name='reviewed',
            name='reviewId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crml_api.Review', unique=True),
        ),
    ]
