# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0016_auto_20180501_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewed',
            name='reviewId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crml_api.Review'),
        ),
        migrations.AlterField(
            model_name='reviewtag',
            name='reviewId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crml_api.Review'),
        ),
    ]
