# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0016_auto_20181005_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='number',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
