# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0016_auto_20180620_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='algorithmId',
        ),
        migrations.AddField(
            model_name='algorithm',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
