# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0017_auto_20180620_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='id',
        ),
        migrations.AddField(
            model_name='algorithm',
            name='algorithmId',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
