# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0017_pullrequest_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='commit',
            name='pr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
