# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0018_auto_20180501_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='extracted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='is_inline_review',
            field=models.BooleanField(default=False),
        ),
    ]
