# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0018_auto_20180620_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='description',
            new_name='name',
        ),
    ]
