# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0019_auto_20180623_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='predicted',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_predicted', to='crml_api.Tag'),
        ),
    ]
