# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0019_pullrequest_pr_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='pr_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='discussion',
            name='pr_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='discussion',
            name='tag_desc',
            field=models.CharField(default='', max_length=50),
        ),
    ]
