# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0019_auto_20180501_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='extracted',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_inline_review',
        ),
    ]
