# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0020_auto_20180501_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tag',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
