# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0020_auto_20180625_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='accuracy',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
