# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0022_auto_20180625_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='performance',
        ),
        migrations.AddField(
            model_name='review',
            name='trainings_size',
            field=models.IntegerField(default=0),
        ),
    ]
