# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-15 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0022_auto_20181015_0345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='f1',
            new_name='acc',
        ),
    ]
