# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0023_auto_20180504_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_content',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_content_length',
            field=models.IntegerField(default=0),
        ),
    ]
