# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-02 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0024_auto_20180627_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='changed',
            field=models.BooleanField(default=False),
        ),
    ]
