# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crml_api', '0024_auto_20180504_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='value',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
